### ISSUE TITLE
Whats your plan with this project?

### ISSUE THREAD

**Issue by wordyallen** [actix/actix-mqtt#1]
Hi. I'm looking for an mqtt broker.  The  example looks very promising.
- Is it ready to use?
- If not, are you open to help?
- Are you going to do releases?
- Documentation?

**Comment by fafhrd91** [comment]
i didnt work on subscribe/unsubscribe yet. this is only missing piece before release. i am building production system that uses actix-mqtt.

but help is always welcomed!

**Comment by fafhrd91** [comment]
if you have more questions as in chat.
